[package]
name = "ugui-r-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { version = "0.29.4", features = ["rwh_05"]}
env_logger = "0.10"
num = "0.4.1"
thread_local = "1.1.7"
softbuffer = "0.4.0"
wgpu = "0.18.0"
config = { version = "0.13.4", features = [] }
wasm-bindgen = "0.2.89"
web-sys = { version = "0.3.64", features = [] }
pollster = "0.3.0"
wasm-bindgen-futures = "0.4.39"
